version: '3.4'

services:
  newgatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  customer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  employee.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

